#!/bin/bash
#
# Fail2ban Module
# Install, configure, and manage fail2ban
#

# Module metadata
module_info() {
    echo "Fail2ban|Install and configure fail2ban intrusion prevention"
}

# Configuration paths
FAIL2BAN_CONF="/etc/fail2ban/fail2ban.conf"
JAIL_LOCAL="/etc/fail2ban/jail.local"
JAIL_D="/etc/fail2ban/jail.d"

# Check if fail2ban is installed
check_fail2ban_installed() {
    command_exists fail2ban-client
}

# Install fail2ban
install_fail2ban() {
    if check_fail2ban_installed; then
        ui_msgbox "Info" "Fail2ban is already installed"
        return 0
    fi

    if ! require_root; then
        return 1
    fi

    if ui_yesno "Install Fail2ban" "Would you like to install fail2ban?"; then
        ui_infobox "Installing" "Installing fail2ban..."
        if install_packages fail2ban; then
            # Enable and start service
            systemctl enable fail2ban
            systemctl start fail2ban

            log_info "Fail2ban installed and started"
            ui_msgbox "Success" "Fail2ban installed successfully.\n\nService is now running."
        else
            ui_msgbox "Error" "Failed to install fail2ban"
            return 1
        fi
    fi
}

# Uninstall fail2ban
uninstall_fail2ban() {
    if ! check_fail2ban_installed; then
        ui_msgbox "Info" "Fail2ban is not installed"
        return 0
    fi

    if ! require_root; then
        return 1
    fi

    if ui_yesno "Uninstall Fail2ban" "Are you sure you want to uninstall fail2ban?\n\nThis will remove all configuration."; then
        systemctl stop fail2ban
        systemctl disable fail2ban

        if remove_packages fail2ban; then
            # Ask to remove config
            if ui_yesno "Remove Config" "Remove configuration files too?"; then
                rm -rf /etc/fail2ban
            fi

            log_info "Fail2ban uninstalled"
            ui_msgbox "Success" "Fail2ban has been uninstalled"
        else
            ui_msgbox "Error" "Failed to uninstall fail2ban"
        fi
    fi
}

# Show fail2ban status
show_status() {
    if ! check_fail2ban_installed; then
        ui_msgbox "Error" "Fail2ban is not installed"
        return 1
    fi

    local info=""
    info+="=== Fail2ban Status ===\n\n"

    # Service status
    if service_is_running fail2ban; then
        info+="Service:      Running\n"
    else
        info+="Service:      Stopped\n"
    fi

    # Version
    local version
    version=$(fail2ban-client --version 2>&1 | head -1)
    info+="Version:      $version\n\n"

    # Overall status
    info+="=== Active Jails ===\n\n"
    local status
    status=$(fail2ban-client status 2>&1)
    info+="$status\n"

    echo -e "$info" > /tmp/fail2ban_status.txt
    ui_textbox "Fail2ban Status" /tmp/fail2ban_status.txt
    rm -f /tmp/fail2ban_status.txt
}

# Show jail status
show_jail_status() {
    if ! check_fail2ban_installed; then
        ui_msgbox "Error" "Fail2ban is not installed"
        return 1
    fi

    # Get list of jails
    local jails
    jails=$(fail2ban-client status 2>/dev/null | grep "Jail list:" | sed 's/.*Jail list:\s*//' | tr ',' '\n' | tr -d ' ')

    if [[ -z "$jails" ]]; then
        ui_msgbox "Info" "No active jails"
        return
    fi

    # Build menu
    local jail_list=()
    for jail in $jails; do
        jail_list+=("$jail" "$jail")
    done

    local selected
    selected=$(ui_menu "Jail Status" "Select jail to view:" "${jail_list[@]}") || return

    # Show jail details
    local jail_status
    jail_status=$(fail2ban-client status "$selected" 2>&1)

    echo -e "=== Jail: $selected ===\n\n$jail_status" > /tmp/jail_status.txt
    ui_textbox "Jail Status: $selected" /tmp/jail_status.txt
    rm -f /tmp/jail_status.txt
}

# Create or update jail.local
ensure_jail_local() {
    if [[ ! -f "$JAIL_LOCAL" ]]; then
        cat > "$JAIL_LOCAL" << 'EOF'
# Fail2ban local configuration
# Generated by Server Manager

[DEFAULT]
# Ban time in seconds (default: 10 minutes)
bantime = 600

# Find time window in seconds
findtime = 600

# Max retries before ban
maxretry = 5

# Action to take
banaction = iptables-multiport

# Email settings (optional)
#destemail = admin@example.com
#sender = fail2ban@example.com
#mta = sendmail

EOF
        log_info "Created $JAIL_LOCAL"
    fi
}

# Configure default settings
configure_defaults() {
    if ! require_root; then
        return 1
    fi

    if ! check_fail2ban_installed; then
        ui_msgbox "Error" "Fail2ban is not installed"
        return 1
    fi

    ensure_jail_local

    while true; do
        local choice
        choice=$(ui_menu "Default Settings" "Configure default settings:" \
            "bantime" "Ban time" \
            "findtime" "Find time window" \
            "maxretry" "Max retries" \
            "action" "Ban action" \
            "email" "Email notifications") || break

        case "$choice" in
            bantime)
                local bantime
                bantime=$(ui_inputbox "Ban Time" "Enter ban time in seconds\n(e.g., 600 = 10 min, 3600 = 1 hour, -1 = permanent):" "600") || continue

                sed -i "s/^bantime = .*/bantime = $bantime/" "$JAIL_LOCAL"
                log_info "Ban time set to: $bantime"
                ui_msgbox "Success" "Ban time set to: $bantime seconds"
                ;;

            findtime)
                local findtime
                findtime=$(ui_inputbox "Find Time" "Enter find time window in seconds:" "600") || continue

                sed -i "s/^findtime = .*/findtime = $findtime/" "$JAIL_LOCAL"
                log_info "Find time set to: $findtime"
                ui_msgbox "Success" "Find time set to: $findtime seconds"
                ;;

            maxretry)
                local maxretry
                maxretry=$(ui_inputbox "Max Retries" "Enter max retries before ban:" "5") || continue

                sed -i "s/^maxretry = .*/maxretry = $maxretry/" "$JAIL_LOCAL"
                log_info "Max retries set to: $maxretry"
                ui_msgbox "Success" "Max retries set to: $maxretry"
                ;;

            action)
                local action
                action=$(ui_radiolist "Ban Action" "Select ban action:" \
                    "iptables-multiport" "IPTables multiport" "on" \
                    "iptables-allports" "IPTables all ports" "off" \
                    "firewallcmd-multiport" "Firewalld multiport" "off" \
                    "ufw" "UFW" "off") || continue

                sed -i "s/^banaction = .*/banaction = $action/" "$JAIL_LOCAL"
                log_info "Ban action set to: $action"
                ui_msgbox "Success" "Ban action set to: $action"
                ;;

            email)
                local email
                email=$(ui_inputbox "Destination Email" "Enter email for notifications\n(leave empty to disable):") || continue

                if [[ -n "$email" ]]; then
                    if grep -q "^destemail" "$JAIL_LOCAL"; then
                        sed -i "s/^destemail = .*/destemail = $email/" "$JAIL_LOCAL"
                    elif grep -q "^#destemail" "$JAIL_LOCAL"; then
                        sed -i "s/^#destemail = .*/destemail = $email/" "$JAIL_LOCAL"
                    else
                        echo "destemail = $email" >> "$JAIL_LOCAL"
                    fi
                    log_info "Email notifications set to: $email"
                    ui_msgbox "Success" "Email set to: $email"
                else
                    sed -i "s/^destemail = .*/#destemail = admin@example.com/" "$JAIL_LOCAL"
                    ui_msgbox "Success" "Email notifications disabled"
                fi
                ;;
        esac
    done

    # Reload fail2ban
    fail2ban-client reload
}

# Enable a jail
enable_jail() {
    if ! require_root; then
        return 1
    fi

    if ! check_fail2ban_installed; then
        ui_msgbox "Error" "Fail2ban is not installed"
        return 1
    fi

    # Common jails
    local jail
    jail=$(ui_menu "Enable Jail" "Select jail to enable:" \
        "sshd" "SSH daemon" \
        "apache-auth" "Apache authentication" \
        "apache-badbots" "Apache bad bots" \
        "apache-noscript" "Apache no script" \
        "apache-overflows" "Apache overflows" \
        "nginx-http-auth" "Nginx HTTP auth" \
        "nginx-botsearch" "Nginx bot search" \
        "postfix" "Postfix SMTP" \
        "dovecot" "Dovecot IMAP/POP3" \
        "mysql-auth" "MySQL authentication" \
        "custom" "Custom jail name") || return

    if [[ "$jail" == "custom" ]]; then
        jail=$(ui_inputbox "Custom Jail" "Enter jail name:") || return
    fi

    # Create jail config
    local jail_file="$JAIL_D/${jail}.local"

    # Get settings
    local port=""
    local logpath=""
    local maxretry="5"
    local bantime="600"

    case "$jail" in
        sshd)
            port="ssh"
            logpath="/var/log/auth.log"
            ;;
        apache-auth)
            port="http,https"
            logpath="/var/log/apache2/error.log"
            ;;
        apache-badbots|apache-noscript|apache-overflows)
            port="http,https"
            logpath="/var/log/apache2/access.log"
            ;;
        nginx-http-auth)
            port="http,https"
            logpath="/var/log/nginx/error.log"
            ;;
        nginx-botsearch)
            port="http,https"
            logpath="/var/log/nginx/access.log"
            ;;
        postfix)
            port="smtp,465,submission"
            logpath="/var/log/mail.log"
            ;;
        dovecot)
            port="pop3,pop3s,imap,imaps"
            logpath="/var/log/mail.log"
            ;;
        mysql-auth)
            port="3306"
            logpath="/var/log/mysql/error.log"
            ;;
        *)
            port=$(ui_inputbox "Port" "Enter port(s) to protect (comma-separated):") || return
            logpath=$(ui_inputbox "Log Path" "Enter log file path:") || return
            ;;
    esac

    # Custom settings
    if ui_yesno "Custom Settings" "Customize max retries and ban time?"; then
        maxretry=$(ui_inputbox "Max Retries" "Enter max retries:" "$maxretry") || maxretry="5"
        bantime=$(ui_inputbox "Ban Time" "Enter ban time in seconds:" "$bantime") || bantime="600"
    fi

    # Create jail configuration
    cat > "$jail_file" << EOF
[$jail]
enabled = true
port = $port
logpath = $logpath
maxretry = $maxretry
bantime = $bantime
EOF

    # Reload fail2ban
    if fail2ban-client reload 2>&1; then
        log_info "Enabled jail: $jail"
        ui_msgbox "Success" "Jail '$jail' enabled.\n\nPort: $port\nLog: $logpath\nMax retries: $maxretry\nBan time: $bantime"
    else
        ui_msgbox "Error" "Failed to enable jail. Check configuration."
        rm -f "$jail_file"
    fi
}

# Disable a jail
disable_jail() {
    if ! require_root; then
        return 1
    fi

    if ! check_fail2ban_installed; then
        ui_msgbox "Error" "Fail2ban is not installed"
        return 1
    fi

    # Get active jails
    local jails
    jails=$(fail2ban-client status 2>/dev/null | grep "Jail list:" | sed 's/.*Jail list:\s*//' | tr ',' '\n' | tr -d ' ')

    if [[ -z "$jails" ]]; then
        ui_msgbox "Info" "No active jails to disable"
        return
    fi

    # Build menu
    local jail_list=()
    for jail in $jails; do
        jail_list+=("$jail" "$jail")
    done

    local selected
    selected=$(ui_menu "Disable Jail" "Select jail to disable:" "${jail_list[@]}") || return

    if ui_yesno "Confirm" "Disable jail '$selected'?"; then
        # Remove jail config or set enabled = false
        local jail_file="$JAIL_D/${selected}.local"

        if [[ -f "$jail_file" ]]; then
            rm -f "$jail_file"
        else
            # Create disabled config
            echo -e "[$selected]\nenabled = false" > "$jail_file"
        fi

        fail2ban-client reload

        log_info "Disabled jail: $selected"
        ui_msgbox "Success" "Jail '$selected' disabled"
    fi
}

# Ban an IP manually
ban_ip() {
    if ! require_root; then
        return 1
    fi

    if ! check_fail2ban_installed; then
        ui_msgbox "Error" "Fail2ban is not installed"
        return 1
    fi

    # Get active jails
    local jails
    jails=$(fail2ban-client status 2>/dev/null | grep "Jail list:" | sed 's/.*Jail list:\s*//' | tr ',' '\n' | tr -d ' ')

    if [[ -z "$jails" ]]; then
        ui_msgbox "Info" "No active jails"
        return
    fi

    # Select jail
    local jail_list=()
    for jail in $jails; do
        jail_list+=("$jail" "$jail")
    done

    local selected_jail
    selected_jail=$(ui_menu "Select Jail" "Select jail to ban IP in:" "${jail_list[@]}") || return

    # Get IP
    local ip
    ip=$(ui_inputbox "Ban IP" "Enter IP address to ban:") || return

    if ! validate_ip "$ip"; then
        ui_msgbox "Error" "Invalid IP address"
        return 1
    fi

    # Ban the IP
    if fail2ban-client set "$selected_jail" banip "$ip" 2>&1; then
        log_info "Banned IP $ip in jail $selected_jail"
        ui_msgbox "Success" "IP $ip banned in jail '$selected_jail'"
    else
        ui_msgbox "Error" "Failed to ban IP"
    fi
}

# Unban an IP
unban_ip() {
    if ! require_root; then
        return 1
    fi

    if ! check_fail2ban_installed; then
        ui_msgbox "Error" "Fail2ban is not installed"
        return 1
    fi

    # Get active jails
    local jails
    jails=$(fail2ban-client status 2>/dev/null | grep "Jail list:" | sed 's/.*Jail list:\s*//' | tr ',' '\n' | tr -d ' ')

    if [[ -z "$jails" ]]; then
        ui_msgbox "Info" "No active jails"
        return
    fi

    # Select jail
    local jail_list=()
    for jail in $jails; do
        jail_list+=("$jail" "$jail")
    done

    local selected_jail
    selected_jail=$(ui_menu "Select Jail" "Select jail to unban IP from:" "${jail_list[@]}") || return

    # Show currently banned IPs
    local banned
    banned=$(fail2ban-client status "$selected_jail" 2>/dev/null | grep "Banned IP" | sed 's/.*Banned IP list:\s*//')

    if [[ -z "$banned" || "$banned" == " " ]]; then
        ui_msgbox "Info" "No banned IPs in jail '$selected_jail'"
        return
    fi

    ui_msgbox "Banned IPs" "Currently banned in $selected_jail:\n\n$banned"

    # Get IP to unban
    local ip
    ip=$(ui_inputbox "Unban IP" "Enter IP address to unban:") || return

    # Unban the IP
    if fail2ban-client set "$selected_jail" unbanip "$ip" 2>&1; then
        log_info "Unbanned IP $ip from jail $selected_jail"
        ui_msgbox "Success" "IP $ip unbanned from jail '$selected_jail'"
    else
        ui_msgbox "Error" "Failed to unban IP"
    fi
}

# Show banned IPs
show_banned() {
    if ! check_fail2ban_installed; then
        ui_msgbox "Error" "Fail2ban is not installed"
        return 1
    fi

    local info=""
    info+="=== Banned IPs ===\n\n"

    # Get all jails
    local jails
    jails=$(fail2ban-client status 2>/dev/null | grep "Jail list:" | sed 's/.*Jail list:\s*//' | tr ',' '\n' | tr -d ' ')

    if [[ -z "$jails" ]]; then
        ui_msgbox "Info" "No active jails"
        return
    fi

    for jail in $jails; do
        local banned
        banned=$(fail2ban-client status "$jail" 2>/dev/null | grep "Banned IP" | sed 's/.*Banned IP list:\s*//')

        info+="Jail: $jail\n"
        if [[ -n "$banned" && "$banned" != " " ]]; then
            info+="  Banned: $banned\n"
        else
            info+="  Banned: (none)\n"
        fi
        info+="\n"
    done

    echo -e "$info" > /tmp/banned_ips.txt
    ui_textbox "Banned IPs" /tmp/banned_ips.txt
    rm -f /tmp/banned_ips.txt
}

# Quick setup with common jails
quick_setup() {
    if ! require_root; then
        return 1
    fi

    # Install if needed
    if ! check_fail2ban_installed; then
        if ! ui_yesno "Install Fail2ban" "Fail2ban is not installed.\n\nInstall it now?"; then
            return
        fi
        install_fail2ban || return 1
    fi

    # Select jails to enable
    local jails
    jails=$(ui_checklist "Quick Setup" "Select jails to enable:" \
        "sshd" "SSH daemon (recommended)" "on" \
        "apache-auth" "Apache authentication" "off" \
        "apache-badbots" "Apache bad bots" "off" \
        "nginx-http-auth" "Nginx HTTP auth" "off" \
        "postfix" "Postfix SMTP" "off" \
        "dovecot" "Dovecot IMAP/POP3" "off") || return

    if [[ -z "$jails" ]]; then
        ui_msgbox "Info" "No jails selected"
        return
    fi

    ensure_jail_local

    # Enable selected jails
    local enabled_jails=""
    for jail in $jails; do
        jail=$(echo "$jail" | tr -d '"')

        local port=""
        local logpath=""

        case "$jail" in
            sshd)
                port="ssh"
                logpath="/var/log/auth.log"
                ;;
            apache-auth)
                port="http,https"
                logpath="/var/log/apache2/error.log"
                ;;
            apache-badbots)
                port="http,https"
                logpath="/var/log/apache2/access.log"
                ;;
            nginx-http-auth)
                port="http,https"
                logpath="/var/log/nginx/error.log"
                ;;
            postfix)
                port="smtp,465,submission"
                logpath="/var/log/mail.log"
                ;;
            dovecot)
                port="pop3,pop3s,imap,imaps"
                logpath="/var/log/mail.log"
                ;;
        esac

        # Create jail config
        cat > "$JAIL_D/${jail}.local" << EOF
[$jail]
enabled = true
port = $port
logpath = $logpath
maxretry = 5
bantime = 600
EOF

        enabled_jails+="• $jail\n"
    done

    # Reload fail2ban
    fail2ban-client reload

    log_info "Quick setup completed"
    ui_msgbox "Setup Complete" "Fail2ban configured with jails:\n\n$enabled_jails\nDefault settings:\n• Max retries: 5\n• Ban time: 10 minutes"
}

# Restart fail2ban
restart_service() {
    if ! require_root; then
        return 1
    fi

    if ! check_fail2ban_installed; then
        ui_msgbox "Error" "Fail2ban is not installed"
        return 1
    fi

    if systemctl restart fail2ban; then
        log_info "Fail2ban service restarted"
        ui_msgbox "Success" "Fail2ban service restarted"
    else
        ui_msgbox "Error" "Failed to restart fail2ban"
    fi
}

# View fail2ban log
view_log() {
    if ! check_fail2ban_installed; then
        ui_msgbox "Error" "Fail2ban is not installed"
        return 1
    fi

    local log_file="/var/log/fail2ban.log"

    if [[ -f "$log_file" ]]; then
        # Show last 100 lines
        tail -100 "$log_file" > /tmp/fail2ban_log.txt
        ui_textbox "Fail2ban Log (last 100 lines)" /tmp/fail2ban_log.txt
        rm -f /tmp/fail2ban_log.txt
    else
        ui_msgbox "Info" "Log file not found: $log_file"
    fi
}

# Main module function
module_main() {
    while true; do
        local choice
        choice=$(ui_menu "Fail2ban" "Select operation:" \
            "quick" "Quick setup" \
            "status" "Show status" \
            "jail-status" "Show jail status" \
            "banned" "Show banned IPs" \
            "install" "Install fail2ban" \
            "uninstall" "Uninstall fail2ban" \
            "defaults" "Configure defaults" \
            "enable" "Enable jail" \
            "disable" "Disable jail" \
            "ban" "Ban IP manually" \
            "unban" "Unban IP" \
            "log" "View log" \
            "restart" "Restart service") || break

        case "$choice" in
            quick)       quick_setup ;;
            status)      show_status ;;
            jail-status) show_jail_status ;;
            banned)      show_banned ;;
            install)     install_fail2ban ;;
            uninstall)   uninstall_fail2ban ;;
            defaults)    configure_defaults ;;
            enable)      enable_jail ;;
            disable)     disable_jail ;;
            ban)         ban_ip ;;
            unban)       unban_ip ;;
            log)         view_log ;;
            restart)     restart_service ;;
        esac
    done
}
