#!/bin/bash
#
# MOTD Manager Module
# Configure system Message of the Day and shell prompt colors
#

# Module metadata
module_info() {
    echo "MOTD Manager|Configure MOTD banner"
}

# Configuration files
MOTD_SCRIPT="/etc/update-motd.d/00-hostname-banner"

# Show status
show_status() {
    local info=""
    info+="=== MOTD Status ===\n\n"

    # MOTD banner
    if [[ -f "$MOTD_SCRIPT" ]]; then
        info+="Hostname banner: Installed\n"
        local font
        font=$(grep 'FONT=' "$MOTD_SCRIPT" 2>/dev/null | cut -d'"' -f2)
        info+="Font:            ${font:-unknown}\n"
        local hostname_type
        hostname_type=$(grep 'HOSTNAME_TYPE=' "$MOTD_SCRIPT" 2>/dev/null | cut -d'"' -f2)
        info+="Hostname type:   ${hostname_type:-static}\n"
    else
        info+="Hostname banner: Not installed\n"
    fi

    # Other MOTD scripts
    info+="\n=== Active MOTD Scripts ===\n\n"
    if [[ -d /etc/update-motd.d ]]; then
        local scripts
        scripts=$(find /etc/update-motd.d -type f -executable | sort)
        if [[ -n "$scripts" ]]; then
            info+="$scripts\n"
        else
            info+="No executable scripts found\n"
        fi
    else
        info+="/etc/update-motd.d not found\n"
    fi

    echo -e "$info" > /tmp/motd_status.txt
    ui_textbox "MOTD Status" /tmp/motd_status.txt
    rm -f /tmp/motd_status.txt
}

# Show current MOTD
show_current_motd() {
    if [[ -d /etc/update-motd.d ]]; then
        local output
        output=$(run-parts /etc/update-motd.d 2>/dev/null)

        if [[ -n "$output" ]]; then
            echo "$output" > /tmp/current_motd.txt
            ui_textbox "Current MOTD" /tmp/current_motd.txt
            rm -f /tmp/current_motd.txt
        else
            ui_msgbox "Info" "No MOTD content generated"
        fi
    elif [[ -f /etc/motd ]]; then
        ui_textbox "Current MOTD" /etc/motd
    else
        ui_msgbox "Info" "No MOTD configured"
    fi
}

# Preview MOTD with specific font
preview_motd() {
    local font="$1"
    local hostname
    hostname=$(hostname)

    local preview=""
    preview+="\n"

    # Generate ASCII art preview
    if command_exists figlet; then
        preview+=$(figlet -f "$font" "$hostname" 2>/dev/null || echo "$hostname")
    else
        local len=${#hostname}
        local border=$(printf '=%.0s' $(seq 1 $((len + 4))))
        preview+="$border\n"
        preview+="| $hostname |\n"
        preview+="$border"
    fi

    preview+="\n─────────────────────────────────────────\n"
    preview+=" OS:     $(lsb_release -ds 2>/dev/null || cat /etc/os-release 2>/dev/null | grep PRETTY_NAME | cut -d'"' -f2)\n"
    preview+=" Kernel: $(uname -r)\n"
    preview+=" Uptime: $(uptime -p | sed 's/up //')\n"
    preview+=" IP:     $(hostname -I | awk '{print $1}')\n"
    preview+="─────────────────────────────────────────\n"

    echo -e "$preview" > /tmp/motd_preview.txt
    ui_textbox "MOTD Preview (Font: $font)" /tmp/motd_preview.txt
    rm -f /tmp/motd_preview.txt
}

# Install MOTD hostname banner
install_motd_banner() {
    if ! require_root; then
        return 1
    fi

    # Check for figlet
    if ! command_exists figlet; then
        if ui_yesno "Install figlet" "figlet is recommended for ASCII art banners.\n\nInstall it now?"; then
            install_packages figlet
        fi
    fi

    # Select hostname type
    local hostname_type
    hostname_type=$(ui_radiolist "Hostname Type" "Which hostname to display?" \
        "static" "Static hostname (e.g., server01)" "on" \
        "pretty" "Pretty hostname (e.g., Web Server 01)" "off") || return

    # Select font if figlet is available
    local font="small"
    if command_exists figlet; then
        while true; do
            font=$(ui_menu "Select Font" "Choose ASCII art font:" \
                "small" "Small (default)" \
                "standard" "Standard" \
                "big" "Big" \
                "banner" "Banner" \
                "slant" "Slant" \
                "mini" "Mini") || font="small"

            # Show preview
            preview_motd "$font"

            if ui_yesno "Confirm Font" "Use this font: $font?"; then
                break
            fi
        done
    fi

    # Create MOTD script
    cat > "$MOTD_SCRIPT" << 'MOTD_EOF'
#!/bin/bash
#
# Dynamic hostname ASCII banner
# Generated by MOTD Manager
#

HOSTNAME_TYPE="HOSTNAME_TYPE_PLACEHOLDER"
FONT="FONT_PLACEHOLDER"

# Get hostname based on type
if [ "$HOSTNAME_TYPE" = "pretty" ]; then
    HOSTNAME=$(hostnamectl --pretty 2>/dev/null)
    # Fallback to static if pretty is empty
    [ -z "$HOSTNAME" ] && HOSTNAME=$(hostname)
else
    HOSTNAME=$(hostname)
fi

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo ""

# Generate ASCII art
if command -v figlet &>/dev/null; then
    echo -e "${CYAN}"
    figlet -f "$FONT" "$HOSTNAME" 2>/dev/null || echo "$HOSTNAME"
    echo -e "${NC}"
elif command -v toilet &>/dev/null; then
    toilet -f small "$HOSTNAME" 2>/dev/null
else
    # Simple banner
    LEN=${#HOSTNAME}
    BORDER=$(printf '=%.0s' $(seq 1 $((LEN + 4))))
    echo -e "${CYAN}$BORDER${NC}"
    echo -e "${CYAN}| ${YELLOW}$HOSTNAME${CYAN} |${NC}"
    echo -e "${CYAN}$BORDER${NC}"
fi

# System info
echo -e "${GREEN}─────────────────────────────────────────${NC}"
echo -e " ${CYAN}OS:${NC}     $(lsb_release -ds 2>/dev/null || cat /etc/os-release | grep PRETTY_NAME | cut -d'"' -f2)"
echo -e " ${CYAN}Kernel:${NC} $(uname -r)"
echo -e " ${CYAN}Uptime:${NC} $(uptime -p | sed 's/up //')"
echo -e " ${CYAN}IP:${NC}     $(hostname -I | awk '{print $1}')"
echo -e "${GREEN}─────────────────────────────────────────${NC}"
echo ""
MOTD_EOF

    # Replace placeholders
    sed -i "s/FONT_PLACEHOLDER/$font/" "$MOTD_SCRIPT"
    sed -i "s/HOSTNAME_TYPE_PLACEHOLDER/$hostname_type/" "$MOTD_SCRIPT"

    chmod +x "$MOTD_SCRIPT"

    # Disable default MOTD scripts that might conflict
    if [[ -f /etc/update-motd.d/10-help-text ]]; then
        chmod -x /etc/update-motd.d/10-help-text 2>/dev/null
    fi

    log_info "MOTD hostname banner installed with font: $font"
    ui_msgbox "Success" "MOTD hostname banner installed.\n\nThe banner will automatically update when hostname changes.\n\nReconnect to SSH to see the new banner."
}

# Remove MOTD banner
remove_motd_banner() {
    if ! require_root; then
        return 1
    fi

    if [[ -f "$MOTD_SCRIPT" ]]; then
        rm -f "$MOTD_SCRIPT"
        log_info "MOTD hostname banner removed"
        ui_msgbox "Success" "MOTD hostname banner removed"
    else
        ui_msgbox "Info" "MOTD banner is not installed"
    fi
}

# Manage other MOTD scripts
manage_scripts() {
    if ! require_root; then
        return 1
    fi

    while true; do
        # Get list of scripts
        local scripts=()
        if [[ -d /etc/update-motd.d ]]; then
            while IFS= read -r script; do
                local name
                name=$(basename "$script")
                local status="disabled"
                [[ -x "$script" ]] && status="enabled"
                scripts+=("$name" "$status")
            done < <(find /etc/update-motd.d -type f | sort)
        fi

        if [[ ${#scripts[@]} -eq 0 ]]; then
            ui_msgbox "Info" "No MOTD scripts found"
            return
        fi

        local choice
        choice=$(ui_menu "MOTD Scripts" "Select script to toggle:" "${scripts[@]}") || break

        local script_path="/etc/update-motd.d/$choice"
        if [[ -x "$script_path" ]]; then
            chmod -x "$script_path"
            ui_msgbox "Success" "Disabled: $choice"
        else
            chmod +x "$script_path"
            ui_msgbox "Success" "Enabled: $choice"
        fi
    done
}

# Main module function
module_main() {
    while true; do
        local choice
        choice=$(ui_menu "MOTD Manager" "Select operation:" \
            "status" "Show status" \
            "show" "Show current MOTD" \
            "install" "Install MOTD banner" \
            "remove" "Remove MOTD banner" \
            "scripts" "Manage MOTD scripts") || break

        case "$choice" in
            status)  show_status ;;
            show)    show_current_motd ;;
            install) install_motd_banner ;;
            remove)  remove_motd_banner ;;
            scripts) manage_scripts ;;
        esac
    done
}
